### PR TITLE
Replacing cURL with Guzzle

### PR DESCRIPTION
**Pull request by garnold**
The PHP cURL extension [causes intermittent issues when running on Google App Engine](https://code.google.com/p/googleappengine/issues/detail?id=12451).  Guzzle provides an abstraction layer for HTTP requests, which allows you to change the underlying service without rewriting application code, and is [the recommended way to issue HTTP requests when using PHP on GAE](https://cloud.google.com/appengine/docs/php/issue-requests#issuing_an_http_request).

Guzzle will continue to use cURL if the extension is enabled, and fallback to stream handlers.

### CODE REVIEW

**Comment by garnold** [comment]
@rraman @bubble-thiyagu @geoffreytran @hellokps @skrish Any thoughts on this pull request?

**Comment by saravana-cb** [comment]
Hi there,

We are looking into this pull request. We will give you an update at the earliest.

Thanks & Regards,
Saravana

**Comment by garnold** [comment]
@saravana-cb I just rebased on `upstream/master`. It's been more than a year... any chance you might take a look?

**Comment by ow** [comment]
Would love this... removes another dependency from the stack

**Comment by bubble-thiyagu** [comment]
@garnold @ow Apologies. This dropped off from our radar again. Will bump this up again. Last time we were discussing this, we were wondering whether this will break things for our other users (those not using composer). i.e possibility of they missing out on setting up Guzzle and this problem manifests in runtime.

**Comment by cb-rakesh** [comment]
This has been merged in v3.0.0

**Pull request closed without merging**
