### PR TITLE
fix: create_function is deprecated in php 7.2

### PR DESCRIPTION
**Pull request by hc42**

### CODE REVIEW

**Comment by hc42** [comment]
#20 solved by this

**Comment by eric-famiglietti** [comment]
Hi @saravana-cb, any update on this?

**Comment by senthilki93** [comment]
i dont think this was correct solutions, but i have fixed this by replaced the both functions as i mentioned below in Util.php 
(toCamelCaseFromUnderscore and toUnderscoreFromCamelCase)

https://github.com/chargebee/chargebee-php/blob/master/lib/ChargeBee/Util.php

**Comment by senthilki93** [comment]
i dont think this was correct solutions, but i have fixed this by replaced the both functions as i mentioned below in Util.php 
(toCamelCaseFromUnderscore and toUnderscoreFromCamelCase)

https://github.com/chargebee/chargebee-php/blob/master/lib/ChargeBee/Util.php

**Pull request merged**
