### PR TITLE
Implemented Namespaces

### PR DESCRIPTION
**Pull request by icetee**
Implemented Namespaces for v2.5.9

+ Fix EnvironmentTest assert for the new API version (v2)
+ Use simpletest from composer packagist

**Test:**
`5/5 test cases complete: 24 passes, 0 fails and 0 exceptions.`

Related of #4 #11 #12

### CODE REVIEW

**Comment by hypnotisttom** [comment]
Can this please have its conflicts resolved and get merged in?  I'm eager to use the library with namespaces.

**Comment by valentinfily** [comment]
Can someone resolve the conflicts and merge this please ??

**Comment by s-andronnikov** [comment]
Try this one, namespaces and guzzle merged
[https://github.com/s-andronnikov/chargebee-php](https://github.com/s-andronnikov/chargebee-php)

**Comment by rubas** [comment]
> Yes please, it is 2019 after all.

2021 ... 👎

**Review by FrontEndCoffee — APPROVED** [review]

**Review by davidacosta620 — APPROVED** [review]

**Comment by cb-rakesh** [comment]
This has been merged in v3.0.0

**Pull request closed without merging**
